import { InventoryItem, WorkOrder } from '../types';

export const mockInventoryItems: InventoryItem[] = [
  {
    id: 'INV-001',
    name: 'Industrial HVAC Unit A2',
    category: 'HVAC',
    serialNumber: 'SN-HV-10928',
    location: 'Building B Roof',
    quantity: 1,
    status: 'Active',
    lastMaintained: '2023-10-15',
  },
  {
    id: 'INV-002',
    name: 'Conveyor Belt Motor',
    category: 'Motors',
    serialNumber: 'SN-CB-5541',
    location: 'Warehouse Floor 1',
    quantity: 3,
    status: 'Pending Repair',
    lastMaintained: '2023-08-20',
  },
  {
    id: 'INV-003',
    name: 'Hydraulic Press Pump',
    category: 'Pumps',
    serialNumber: 'SN-HP-998',
    location: 'Assembly Line A',
    quantity: 1,
    status: 'In Maintenance',
    lastMaintained: '2023-11-01',
  },
  {
    id: 'INV-004',
    name: 'Control Panel PLC',
    category: 'Electronics',
    serialNumber: 'SN-PLC-202',
    location: 'Server Room',
    quantity: 5,
    status: 'Active',
    lastMaintained: '2023-11-20',
  },
];

export const mockWorkOrders: WorkOrder[] = [
  {
    id: 'WO-1001',
    title: 'Routine HVAC Filter Replacement',
    description: 'Replace HEPA filters on main air handling unit.',
    assetId: 'INV-001',
    assignedTo: 'John Doe',
    priority: 'Medium',
    status: 'Open',
    createdAt: '2023-11-25',
    dueDate: '2023-12-05',
  },
  {
    id: 'WO-1002',
    title: 'Motor Bearing Squeak',
    description: 'Investigate and lubricate or replace bearings on conveyor motor.',
    assetId: 'INV-002',
    assignedTo: 'Jane Smith',
    priority: 'High',
    status: 'In Progress',
    createdAt: '2023-11-26',
    dueDate: '2023-11-28',
  },
  {
    id: 'WO-1003',
    title: 'Hydraulic Fluid Leak',
    description: 'Locate and seal leak on the primary hydraulic press pump.',
    assetId: 'INV-003',
    assignedTo: 'Mike Johnson',
    priority: 'Critical',
    status: 'On Hold',
    createdAt: '2023-11-22',
    dueDate: '2023-11-24',
  },
  {
    id: 'WO-1004',
    title: 'PLC Firmware Update',
    description: 'Apply security patch 2.4.1 to all active PLCs.',
    assetId: 'INV-004',
    assignedTo: 'Alice Williams',
    priority: 'Low',
    status: 'Completed',
    createdAt: '2023-11-10',
    dueDate: '2023-11-15',
    completedAt: '2023-11-14',
  },
];
